// Auto-generated from the user's wardrobe spreadsheet — do not hand-edit.
const SEED_ITEMS = [
  {
    "id": "seed-001",
    "name": "棕色復古襯衫",
    "category": "top",
    "tags": [
      "短"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2026-07-26",
    "price": 590,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1785024000001
  },
  {
    "id": "seed-002",
    "name": "GU七分牛仔褲",
    "category": "bottom",
    "tags": [
      "短"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2026-04-14",
    "price": 790,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1776124800002
  },
  {
    "id": "seed-003",
    "name": "大力水手印花白T",
    "category": "top",
    "tags": [
      "短"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2026-03-30",
    "price": 596,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1774828800003
  },
  {
    "id": "seed-004",
    "name": "GU深藍針織上衣",
    "category": "top",
    "tags": [
      "長"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2026-01-03",
    "price": 890,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1767398400004
  },
  {
    "id": "seed-005",
    "name": "藍polo衫",
    "category": "top",
    "tags": [
      "長"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2025-11-07",
    "price": 700,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1762473600005
  },
  {
    "id": "seed-006",
    "name": "灰素T",
    "category": "top",
    "tags": [
      "短"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2025-10-26",
    "price": 199,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1761436800006
  },
  {
    "id": "seed-007",
    "name": "灰短褲百搭",
    "category": "bottom",
    "tags": [
      "短"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2025-07-25",
    "price": 398,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1753401600007
  },
  {
    "id": "seed-008",
    "name": "藍色皺摺襯衫🥕",
    "category": "top",
    "tags": [
      "短"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2025-07-12",
    "price": 0,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1752278400008
  },
  {
    "id": "seed-009",
    "name": "UQ膽大黨白T",
    "category": "top",
    "tags": [
      "短"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2025-07-04",
    "price": 490,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1751587200009
  },
  {
    "id": "seed-010",
    "name": "GU淺色牛仔褲",
    "category": "bottom",
    "tags": [
      "長"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2025-06-08",
    "price": 990,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1749340800010
  },
  {
    "id": "seed-011",
    "name": "UQ條紋襯衫 淺棕條紋",
    "category": "top",
    "tags": [
      "短"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2025-06-07",
    "price": 990,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1749254400011
  },
  {
    "id": "seed-012",
    "name": "GU白色基本短袖T",
    "category": "top",
    "tags": [
      "短"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2025-05-23",
    "price": 290,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1747958400012
  },
  {
    "id": "seed-013",
    "name": "Plain me工作薄黑外套",
    "category": "outer",
    "tags": [],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2025-05-09",
    "price": 1190,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1746748800013
  },
  {
    "id": "seed-014",
    "name": "Easy store深灰T 胸前小字",
    "category": "top",
    "tags": [
      "短"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2025-04-18",
    "price": 490,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1744934400014
  },
  {
    "id": "seed-015",
    "name": "Easy store黑屁孩T",
    "category": "top",
    "tags": [
      "短"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2025-04-18",
    "price": 490,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1744934400015
  },
  {
    "id": "seed-016",
    "name": "UQ黑色內褲*2",
    "category": "bottom",
    "tags": [],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2025-03-28",
    "price": 390,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1743120000016
  },
  {
    "id": "seed-017",
    "name": "霓送的復古款帽子",
    "category": "hat",
    "tags": [],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2025-02-18",
    "price": 0,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1739836800017
  },
  {
    "id": "seed-018",
    "name": "灰素面polo",
    "category": "top",
    "tags": [
      "長"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2024-12-28",
    "price": 450,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1735344000018
  },
  {
    "id": "seed-019",
    "name": "黑韓系條紋毛衣",
    "category": "top",
    "tags": [
      "長"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2024-12-28",
    "price": 475,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1735344000019
  },
  {
    "id": "seed-020",
    "name": "紅色雪山圖案帽",
    "category": "hat",
    "tags": [],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2024-12-20",
    "price": 139,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1734652800020
  },
  {
    "id": "seed-021",
    "name": "黑牛仔帽",
    "category": "hat",
    "tags": [],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2024-12-20",
    "price": 119,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1734652800021
  },
  {
    "id": "seed-022",
    "name": "GU灰牛仔長褲",
    "category": "bottom",
    "tags": [
      "長"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2024-12-08",
    "price": 910,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1733616000022
  },
  {
    "id": "seed-023",
    "name": "綠格紋復古系外套",
    "category": "outer",
    "tags": [
      "長"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2024-12-02",
    "price": 1399,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1733097600023
  },
  {
    "id": "seed-024",
    "name": "Converse 1970 經典黑",
    "category": "shoes",
    "tags": [],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2024-11-30",
    "price": 1730,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1732924800024
  },
  {
    "id": "seed-025",
    "name": "白兔子情侶衣",
    "category": "top",
    "tags": [
      "短"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2024-10-25",
    "price": 400,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1729814400025
  },
  {
    "id": "seed-026",
    "name": "綠條紋polo",
    "category": "top",
    "tags": [
      "短"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2024-04-20",
    "price": 480,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1713571200026
  },
  {
    "id": "seed-027",
    "name": "Converse 1970 岩石灰",
    "category": "shoes",
    "tags": [],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2024-02-05",
    "price": 1830,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1707091200027
  },
  {
    "id": "seed-028",
    "name": "軍綠寬工裝褲",
    "category": "bottom",
    "tags": [
      "長"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2024-02-03",
    "price": 550,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1706918400028
  },
  {
    "id": "seed-029",
    "name": "綠色帽踢🥕",
    "category": "top",
    "tags": [
      "長"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2024-01-28",
    "price": 444,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1706400000029
  },
  {
    "id": "seed-030",
    "name": "黑色 皮外套",
    "category": "outer",
    "tags": [
      "長"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2023-12-18",
    "price": 665,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1702857600030
  },
  {
    "id": "seed-031",
    "name": "落肩韓系古巴短襯衫",
    "category": "top",
    "tags": [
      "短"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2023-08-21",
    "price": 380,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1692576000031
  },
  {
    "id": "seed-032",
    "name": "50%藍色襯衫",
    "category": "top",
    "tags": [
      "短"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2023-05-03",
    "price": 499,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1683072000032
  },
  {
    "id": "seed-033",
    "name": "港風薄薄襯衫",
    "category": "top",
    "tags": [
      "短"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2023-04-09",
    "price": 329,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1680998400033
  },
  {
    "id": "seed-034",
    "name": "灰條紋襯衫",
    "category": "top",
    "tags": [
      "短"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2023-04-04",
    "price": 265,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1680566400034
  },
  {
    "id": "seed-035",
    "name": "黑針織背心",
    "category": "top",
    "tags": [],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2023-02-16",
    "price": 690,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1676505600035
  },
  {
    "id": "seed-036",
    "name": "黑西裝外套",
    "category": "outer",
    "tags": [
      "長"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2023-02-16",
    "price": 780,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1676505600036
  },
  {
    "id": "seed-037",
    "name": "灰色短版毛帽",
    "category": "hat",
    "tags": [],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2023-02-04",
    "price": 59,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1675468800037
  },
  {
    "id": "seed-038",
    "name": "藏藍學院針織上衣",
    "category": "top",
    "tags": [
      "長"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2023-01-19",
    "price": 411,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1674086400038
  },
  {
    "id": "seed-039",
    "name": "黑色百搭落地褲",
    "category": "bottom",
    "tags": [
      "長"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2023-01-17",
    "price": 590,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1673913600039
  },
  {
    "id": "seed-040",
    "name": "三孔馬汀鞋",
    "category": "shoes",
    "tags": [],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2023-01-12",
    "price": 2450,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1673481600040
  },
  {
    "id": "seed-041",
    "name": "百搭白色長袖襯衫",
    "category": "top",
    "tags": [
      "長"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2023-01-08",
    "price": 380,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1673136000041
  },
  {
    "id": "seed-042",
    "name": "卡其罩衫",
    "category": "top",
    "tags": [
      "長"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2023-01-08",
    "price": 680,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1673136000042
  },
  {
    "id": "seed-043",
    "name": "咖啡罩衫",
    "category": "top",
    "tags": [
      "長"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2023-01-08",
    "price": 680,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1673136000043
  },
  {
    "id": "seed-044",
    "name": "藍色毛帽",
    "category": "hat",
    "tags": [],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2022-12-25",
    "price": 55,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1671926400044
  },
  {
    "id": "seed-045",
    "name": "卡其棒球帽",
    "category": "hat",
    "tags": [],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2022-12-25",
    "price": 119,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1671926400045
  },
  {
    "id": "seed-046",
    "name": "韓系黑色叉叉臉毛帽",
    "category": "hat",
    "tags": [],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2022-12-25",
    "price": 88,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1671926400046
  },
  {
    "id": "seed-047",
    "name": "白色百搭毛帽",
    "category": "hat",
    "tags": [],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2022-12-25",
    "price": 75,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1671926400047
  },
  {
    "id": "seed-048",
    "name": "50%灰色針織毛衣",
    "category": "top",
    "tags": [
      "長"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2022-12-21",
    "price": 690,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1671580800048
  },
  {
    "id": "seed-049",
    "name": "深卡其燈芯絨長褲",
    "category": "bottom",
    "tags": [
      "長"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2022-12-18",
    "price": 0,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1671321600049
  },
  {
    "id": "seed-050",
    "name": "綠格紋針織外套",
    "category": "outer",
    "tags": [
      "長"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2022-12-17",
    "price": 800,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1671235200050
  },
  {
    "id": "seed-051",
    "name": "滑板鬼大學T",
    "category": "top",
    "tags": [
      "長"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2022-12-17",
    "price": 500,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1671235200051
  },
  {
    "id": "seed-052",
    "name": "New Balance",
    "category": "shoes",
    "tags": [],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2022-12-17",
    "price": 2680,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1671235200052
  },
  {
    "id": "seed-053",
    "name": "50%暖灰衛衣",
    "category": "top",
    "tags": [
      "長"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2022-12-11",
    "price": null,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1670716800053
  },
  {
    "id": "seed-054",
    "name": "50%棕色可愛圖案大學T",
    "category": "top",
    "tags": [
      "長"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2022-12-11",
    "price": null,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1670716800054
  },
  {
    "id": "seed-055",
    "name": "50%黑色雙面大外套",
    "category": "outer",
    "tags": [
      "長"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2022-12-11",
    "price": 1499,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1670716800055
  },
  {
    "id": "seed-056",
    "name": "50%灰色襯衫",
    "category": "top",
    "tags": [
      "長"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2022-12-11",
    "price": null,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1670716800056
  },
  {
    "id": "seed-057",
    "name": "50%黑西裝褲",
    "category": "bottom",
    "tags": [
      "長"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2022-10-02",
    "price": 790,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1664668800057
  },
  {
    "id": "seed-058",
    "name": "50%綠襯衫",
    "category": "top",
    "tags": [
      "短"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2022-10-02",
    "price": 499,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1664668800058
  },
  {
    "id": "seed-059",
    "name": "UQ Arism U 白T",
    "category": "top",
    "tags": [
      "短"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2022-04-24",
    "price": 590,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1650758400059
  },
  {
    "id": "seed-060",
    "name": "薄荷綠古巴襯",
    "category": "top",
    "tags": [
      "短"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2022-04-16",
    "price": 570,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1650067200060
  },
  {
    "id": "seed-061",
    "name": "直條紋黑古巴襯",
    "category": "top",
    "tags": [
      "短"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2022-04-16",
    "price": 570,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1650067200061
  },
  {
    "id": "seed-062",
    "name": "Converse 1970 海軍藍",
    "category": "shoes",
    "tags": [],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2022-04-07",
    "price": 2230,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1649289600062
  },
  {
    "id": "seed-063",
    "name": "灰色西褲",
    "category": "bottom",
    "tags": [
      "長"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2022-03-29",
    "price": 350,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1648512000063
  },
  {
    "id": "seed-064",
    "name": "深藍針織背心",
    "category": "top",
    "tags": [],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2022-03-29",
    "price": 690,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1648512000064
  },
  {
    "id": "seed-065",
    "name": "50% 紫大學T",
    "category": "top",
    "tags": [
      "長"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2022-01-02",
    "price": 690,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1641081600065
  },
  {
    "id": "seed-066",
    "name": "水兵帽 卡其",
    "category": "hat",
    "tags": [],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2021-11-26",
    "price": 280,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1637884800066
  },
  {
    "id": "seed-067",
    "name": "XX長襪",
    "category": "accessory",
    "tags": [
      "長",
      "襪子"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2021-11-26",
    "price": 69,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1637884800067
  },
  {
    "id": "seed-068",
    "name": "白長襪 基本款",
    "category": "accessory",
    "tags": [
      "長",
      "襪子"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2021-11-26",
    "price": 49,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1637884800068
  },
  {
    "id": "seed-069",
    "name": "韓系文字襪 藍線",
    "category": "accessory",
    "tags": [
      "長",
      "襪子"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2021-11-22",
    "price": 45,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1637539200069
  },
  {
    "id": "seed-070",
    "name": "韓系文字襪 紅線",
    "category": "accessory",
    "tags": [
      "長",
      "襪子"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2021-11-22",
    "price": 45,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1637539200070
  },
  {
    "id": "seed-071",
    "name": "韓系文字襪 深藍",
    "category": "accessory",
    "tags": [
      "長",
      "襪子"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2021-11-22",
    "price": 45,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1637539200071
  },
  {
    "id": "seed-072",
    "name": "白中筒襪",
    "category": "accessory",
    "tags": [
      "短",
      "襪子"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2021-09-06",
    "price": 69,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1630886400072
  },
  {
    "id": "seed-073",
    "name": "錐形牛仔褲",
    "category": "bottom",
    "tags": [
      "長"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2021-09-06",
    "price": 680,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1630886400073
  },
  {
    "id": "seed-074",
    "name": "Xctrl 鯉魚白T",
    "category": "top",
    "tags": [
      "短"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2021-09-04",
    "price": 530,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1630713600074
  },
  {
    "id": "seed-075",
    "name": "Whoswear 黑短褲",
    "category": "bottom",
    "tags": [
      "短"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2021-09-02",
    "price": 480,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1630540800075
  },
  {
    "id": "seed-076",
    "name": "Whoswear貓貓T",
    "category": "top",
    "tags": [
      "短"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2021-09-02",
    "price": 480,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1630540800076
  },
  {
    "id": "seed-077",
    "name": "Whoswear 米色襯衫",
    "category": "top",
    "tags": [
      "短"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2021-09-02",
    "price": 590,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1630540800077
  },
  {
    "id": "seed-078",
    "name": "50%白 長襪",
    "category": "accessory",
    "tags": [
      "長",
      "襪子"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2021-08-28",
    "price": 99,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1630108800078
  },
  {
    "id": "seed-079",
    "name": "50%白中筒襪1,2",
    "category": "accessory",
    "tags": [
      "襪子"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2021-08-28",
    "price": 99,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1630108800079
  },
  {
    "id": "seed-080",
    "name": "IAMGOOD漁夫帽",
    "category": "hat",
    "tags": [],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2021-08-28",
    "price": 290,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1630108800080
  },
  {
    "id": "seed-081",
    "name": "2020雲科路跑長襪",
    "category": "accessory",
    "tags": [
      "長",
      "襪子"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2021-08-27",
    "price": 0,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1630022400081
  },
  {
    "id": "seed-082",
    "name": "50%黑 長襪",
    "category": "accessory",
    "tags": [
      "長",
      "襪子"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2021-07-16",
    "price": 99,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1626393600082
  },
  {
    "id": "seed-083",
    "name": "50%夏日祭典 深藍T",
    "category": "top",
    "tags": [
      "短"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2021-07-16",
    "price": 349,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1626393600083
  },
  {
    "id": "seed-084",
    "name": "50% 薄白T",
    "category": "top",
    "tags": [
      "短"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2021-07-16",
    "price": 299,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1626393600084
  },
  {
    "id": "seed-085",
    "name": "50%卡其褲",
    "category": "bottom",
    "tags": [
      "長"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2021-02-09",
    "price": 600,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1612828800085
  },
  {
    "id": "seed-086",
    "name": "50%卡其外套",
    "category": "outer",
    "tags": [
      "長"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2021-02-09",
    "price": 600,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1612828800086
  },
  {
    "id": "seed-087",
    "name": "Uniqlo毛衣",
    "category": "top",
    "tags": [
      "長"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2021-02-02",
    "price": 0,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1612224000087
  },
  {
    "id": "seed-088",
    "name": "Puma運動褲",
    "category": "bottom",
    "tags": [
      "短"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2021-02-02",
    "price": 1100,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1612224000088
  },
  {
    "id": "seed-089",
    "name": "藍綠條紋內褲",
    "category": "accessory",
    "tags": [
      "內褲"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2021-02-02",
    "price": 0,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1612224000089
  },
  {
    "id": "seed-090",
    "name": "短襪2",
    "category": "accessory",
    "tags": [
      "襪子"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2021-02-02",
    "price": 0,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1612224000090
  },
  {
    "id": "seed-091",
    "name": "短襪1",
    "category": "accessory",
    "tags": [
      "襪子"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2021-02-02",
    "price": 0,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1612224000091
  },
  {
    "id": "seed-092",
    "name": "Converse 1970 灰色",
    "category": "shoes",
    "tags": [],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2021-01-28",
    "price": 2480,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1611792000092
  },
  {
    "id": "seed-093",
    "name": "Lativ Keith Haring大學T",
    "category": "top",
    "tags": [
      "長"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2021-01-05",
    "price": 399,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1609804800093
  },
  {
    "id": "seed-094",
    "name": "Lativ發熱褲",
    "category": "bottom",
    "tags": [
      "長"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2021-01-05",
    "price": 299,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1609804800094
  },
  {
    "id": "seed-095",
    "name": "Lativ 可口可樂帽T",
    "category": "top",
    "tags": [
      "長"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2020-12-30",
    "price": 590,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1609286400095
  },
  {
    "id": "seed-096",
    "name": "30th吉他社服",
    "category": "top",
    "tags": [
      "短"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2020-09-29",
    "price": 300,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1601337600096
  },
  {
    "id": "seed-097",
    "name": "Mizuno排球襪",
    "category": "accessory",
    "tags": [
      "襪子"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2020-09-24",
    "price": 210,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1600905600097
  },
  {
    "id": "seed-098",
    "name": "Uniqlo灰色內褲(1-7)",
    "category": "accessory",
    "tags": [
      "內褲"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2020-08-29",
    "price": 200,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1598659200098
  },
  {
    "id": "seed-099",
    "name": "50%卡其短褲",
    "category": "bottom",
    "tags": [
      "短"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2020-08-12",
    "price": 300,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1597190400099
  },
  {
    "id": "seed-100",
    "name": "Converse All Star 紅",
    "category": "shoes",
    "tags": [],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2020-07-17",
    "price": 1020,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1594944000100
  },
  {
    "id": "seed-101",
    "name": "Adidas慢跑鞋",
    "category": "shoes",
    "tags": [],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2020-06-07",
    "price": 2790,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1591488000101
  },
  {
    "id": "seed-102",
    "name": "GU棕色長褲",
    "category": "bottom",
    "tags": [
      "長"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "",
    "price": null,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "clean",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1577836800102
  },
  {
    "id": "seed-103",
    "name": "微落地牛仔褲",
    "category": "bottom",
    "tags": [
      "長"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2023-02-04",
    "price": 495,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "retired",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1675468800103
  },
  {
    "id": "seed-104",
    "name": "米白燈芯絨長褲",
    "category": "bottom",
    "tags": [
      "長"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2023-01-30",
    "price": 499,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "retired",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1675036800104
  },
  {
    "id": "seed-105",
    "name": "直筒奶油褲",
    "category": "bottom",
    "tags": [
      "長"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2022-04-16",
    "price": 699,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "retired",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1650067200105
  },
  {
    "id": "seed-106",
    "name": "滿版葉草花襯衫",
    "category": "top",
    "tags": [
      "短"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2022-04-10",
    "price": 330,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "retired",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1649548800106
  },
  {
    "id": "seed-107",
    "name": "深藍七分袖",
    "category": "top",
    "tags": [
      "短"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2022-03-29",
    "price": 299,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "retired",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1648512000107
  },
  {
    "id": "seed-108",
    "name": "黑直筒工裝褲",
    "category": "bottom",
    "tags": [
      "長"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2021-09-06",
    "price": 780,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "retired",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1630886400108
  },
  {
    "id": "seed-109",
    "name": "50%米色衛衣",
    "category": "top",
    "tags": [
      "長"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2021-02-09",
    "price": 500,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "retired",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1612828800109
  },
  {
    "id": "seed-110",
    "name": "Lativ米奇帽T",
    "category": "top",
    "tags": [
      "長"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2021-01-05",
    "price": 399,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "retired",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1609804800110
  },
  {
    "id": "seed-111",
    "name": "藍色PEAK大學T",
    "category": "top",
    "tags": [
      "長"
    ],
    "image": null,
    "imageBack": null,
    "purchaseDate": "2020-11-27",
    "price": 500,
    "wearCount": 0,
    "totalWearCount": 0,
    "status": "retired",
    "lastWornDate": null,
    "wornToday": false,
    "wearHistory": [],
    "createdAt": 1606435200111
  }
];
